import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-br" className={`${GeistSans.variable}`}>
      <body className="bg-cinza-fundo">
        <div
          className="mx-auto"
          style={{
            width: "min(1400px,100%)",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
